import { Invoice } from '../types';
import { createPDF } from './pdfEngine';
import { formatCurrency } from '../../lib/localeFormatters';
import { generateLegalClause } from '../legal/clauseGenerator';

export async function generatePDFReceipt(invoice: Invoice): Promise<Buffer> {
  const receiptTemplate = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Receipt for Invoice #${invoice.id}</title>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        .header { text-align: center; margin-bottom: 2rem; }
        .details { display: flex; justify-content: space-between; margin-bottom: 2rem; }
        .items { width: 100%; border-collapse: collapse; margin-bottom: 2rem; }
        .items th, .items td { padding: 0.75rem; text-align: left; border-bottom: 1px solid #ddd; }
        .total { text-align: right; font-weight: bold; font-size: 1.2rem; }
        .footer { margin-top: 3rem; font-size: 0.8rem; color: #666; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>InvoiceGod Receipt</h1>
        <p>Invoice #${invoice.id}</p>
      </div>

      <div class="details">
        <div>
          <strong>Issued To:</strong><br>
          ${invoice.client.name}<br>
          ${invoice.client.email}<br>
          ${invoice.client.address || ''}
        </div>
        <div>
          <strong>Date:</strong> ${new Date(invoice.date).toLocaleDateString()}<br>
          <strong>Status:</strong> ${invoice.status}<br>
          ${invoice.paymentMethod ? `<strong>Payment Method:</strong> ${invoice.paymentMethod}` : ''}
        </div>
      </div>

      <table class="items">
        <thead>
          <tr>
            <th>Description</th>
            <th>Quantity</th>
            <th>Unit Price</th>
            <th>Amount</th>
          </tr>
        </thead>
        <tbody>
          ${invoice.items.map(item => `
            <tr>
              <td>${item.description}</td>
              <td>${item.quantity || 1}</td>
              <td>${formatCurrency(item.rate, invoice.currency, invoice.client.locale)}</td>
              <td>${formatCurrency(item.amount, invoice.currency, invoice.client.locale)}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <div class="total">
        Total: ${formatCurrency(invoice.total, invoice.currency, invoice.client.locale)}
      </div>

      <div class="footer">
        <p>${generateLegalClause('receiptFooter', invoice.jurisdiction)}</p>
        <p>Generated by InvoiceGod on ${new Date().toLocaleString()}</p>
      </div>
    </body>
    </html>
  `;

  return createPDF(receiptTemplate);
}